sources:
  my-pg-source:
    kind: postgres
    host: db  # Changed from 127.0.0.1 to the service name
    port: 5432
    database: toolbox_db
    user: toolbox_user
    password: my-password

tools:
  create-note:
    kind: postgres-sql
    source: my-pg-source
    description: Create a new text note with content and category
    parameters:
      - name: content
        type: string
        description: The text content of the note
      - name: category
        type: string
        description: Category for the note
      - name: action_date
        type: string
        description: Optional action date (YYYY-MM-DD HH:MM:SS format)
    statement: |
      INSERT INTO notes (content, category, action_date)
      VALUES ($1, $2, CAST($3 AS TIMESTAMPTZ));

  search-notes-by-category:
    kind: postgres-sql
    source: my-pg-source
    description: Search notes by category name
    parameters:
      - name: category
        type: string
        description: Category name to search for
    statement: |
      SELECT * FROM notes 
      WHERE category ILIKE '%' || $1 || '%';

  search-notes-by-status:
    kind: postgres-sql
    source: my-pg-source
    description: Search notes by their current status
    parameters:
      - name: status
        type: string
        description: Status to filter by (Open, Completed, Deferred)
    statement: |
      SELECT * FROM notes
      WHERE status = $1::entry_status;

  update-note-status:
    kind: postgres-sql
    source: my-pg-source
    description: Update the status of a note
    parameters:
      - name: note_id
        type: string
        description: ID of the note to update
      - name: new_status
        type: string
        description: New status (Open, Completed, Deferred)
    statement: |
      UPDATE notes
      SET status = $2::entry_status
      WHERE id = CAST($1 AS INTEGER);

  set-note-action-date:
    kind: postgres-sql
    source: my-pg-source
    description: Set or update the action date for a note
    parameters:
      - name: note_id
        type: string
        description: ID of the note to update
      - name: action_date
        type: string
        description: New action date (YYYY-MM-DD HH:MM:SS format)
    statement: |
      UPDATE notes
      SET action_date = CAST($2 AS TIMESTAMPTZ)
      WHERE id = CAST($1 AS INTEGER);

  search-notes-by-action-range:
    kind: postgres-sql
    source: my-pg-source
    description: Find notes with action dates in a specified range
    parameters:
      - name: start_date
        type: string
        description: Start of date range (YYYY-MM-DD format)
      - name: end_date
        type: string
        description: End of date range (YYYY-MM-DD format)
    statement: |
      SELECT * FROM notes
      WHERE action_date BETWEEN CAST($1 AS DATE) AND CAST($2 AS DATE);

toolsets:
  note-management-toolset:
    - create-note
    - search-notes-by-category
    - search-notes-by-status
    - update-note-status
    - set-note-action-date
    - search-notes-by-action-range